# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 
dir: rtl
# Title of the Site
title: مدونة صويلح
# Description of the Site
description: تدريس الرياضيات
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: 
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: rezazsouilah@gmail.com
facebook_username: rezak.souilah.5
twitter_username: RezakSouilah
instagram_username: 
linkedin_username: souilah-rezak-ens-kouba-b01336176
github_username:  https://github.com/rezazsouilah
youtube_channel_id: UC5koK8t_zhHArmZ1WWF80MQ
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
disqus-shortname:
# Name of the Author
author-name: صويلح رزاق
# URL for the Image of the Author
author-image: img/souilah.png
# 60 Words About the Author
author-about:  Hi, I am Rezak Souilah, teacher of Mathematics at University Yahia Fares, Médéa, Algeria. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/rezazsouilah

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
